version: "3.9"

services:
  db:
    image: postgres:17
    container_name: ecommerce-db
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce_net
    restart: always

  analytic:
    build: ./analitic-service
    container_name: ecommerce-analytic
    command: bash -c "./entrypoint.sh"
    ports:
      - "8001:8080"
    depends_on:
      - db
    networks:
      - ecommerce_net
    restart: always

  gateway:
    build: ./ecomerce-gateway-service
    container_name: ecommerce-gateway
    ports:
      - "8000:8000"
    volumes:
      - ./ecomerce-gateway-service:/app
    environment:
      SERVICE_ANALITICA: http://analytic:8080
      SERVICE_ORDER: http://order:8080
    depends_on:
      - analytic
      - order
    networks:
      - ecommerce_net
    restart: always

  order:
    image: dockerilham117/projects-order:latest
    container_name: ecommerce-order
    ports:
      - "8002:8080"
    depends_on:
      - db
    networks:
      - ecommerce_net
    restart: always

volumes:
  postgres_data:

networks:
  ecommerce_net:
    driver: bridge
