name: Microservices CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analitic:
    name: Analitic Service CI/CD
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: analitic_db
        options: >-
          --health-cmd "pg_isready -U user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./analitic

      - name: Run tests
        run: pytest tests/
        working-directory: ./analitic

      - name: Build Docker image
        run: docker build -t dockerilham117/projects-analitic:latest ./analitic

      - name: Docker login
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: docker push dockerilham117/projects-analitic:latest

  gateway:
    name: Gateway Service CI/CD
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: gateway_db
        options: >-
          --health-cmd "pg_isready -U user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./ecomerce-gateway-service

      - name: Set environment variables
        run: |
          echo "DATABASE_URL=postgres://user:password@localhost:5432/gateway_db" >> $GITHUB_ENV

      - name: Run tests
        run: pytest tests/
        working-directory: ./ecomerce-gateway-service

      - name: Build Docker image
        run: docker build -t dockerilham117/projects-gateway:latest ./ecomerce-gateway-service

      - name: Docker login
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: docker push dockerilham117/projects-gateway:latest

  order:
    name: Order Service CI/CD
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: order_db
        options: >-
          --health-cmd "pg_isready -U user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./Ecommerce-order-service

      - name: Set environment variables
        run: |
          echo "DATABASE_URL=postgres://user:password@localhost:5432/order_db" >> $GITHUB_ENV
          echo "POSTGRES_DB=order_db" >> $GITHUB_ENV
          echo "POSTGRES_USER=user" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=password" >> $GITHUB_ENV

      - name: Run tests
        run: python manage.py test
        working-directory: ./Ecommerce-order-service

      - name: Build Docker image
        run: docker build -t dockerilham117/projects-order:latest ./Ecommerce-order-service

      - name: Docker login
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: docker push dockerilham117/projects-order:latest
