name: Order Service CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  order:
    name: Order Service CI/CD
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: order_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # 1️⃣ Checkout repository
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # 2️⃣ Python setup
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: pip install --upgrade pip

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./order-service

      # 4️⃣ Set environment variables
      - name: Set environment variables
        run: |
          echo "DATABASE_URL=postgres://user:password@localhost:5432/order_db" >> $GITHUB_ENV
          echo "POSTGRES_DB=order_db" >> $GITHUB_ENV
          echo "POSTGRES_USER=user" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=password" >> $GITHUB_ENV

      # 5️⃣ Run tests (Python/Django)
      - name: Run tests
        run: python manage.py test
        working-directory: ./order-service

      # 6️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t dockerilham117/projects-order:latest ./order-service

      # 7️⃣ Docker login
      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 8️⃣ Push Docker image
      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: docker push dockerilham117/projects-order:latest
