name: Order Service CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  order:
    name: Order Service CI/CD
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # 2️⃣ Docker Buildx (build və multi-platform dəstəyi üçün)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t dockerilham117/projects-order:latest ./ecommerce-order-service

      # 4️⃣ Push Docker image
      - if: github.ref == 'refs/heads/main'
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push dockerilham117/projects-order:latest
