name: Order Service CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  order:
    name: Order Service CI/CD
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # 2️⃣ Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ✅ 3️⃣ Build Docker image (düzgün qovluq adı ilə)
      - name: Build Docker image
        run: docker build -t dockerilham117/projects-order:latest ./order-service

      # 4️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5️⃣ Push Docker image
      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: docker push dockerilham117/projects-order:latest
